### ISSUE TITLE
Enable Travis CI

### ISSUE THREAD

**Issue by Ne4istb** [VerbalExpressions/DartVerbalExpressions#4]
To include Travis CI somebody with repo admin rights have to enable this repo in Travis settings on https://travis-ci.org/profile/VerbalExpressions. 
@ionutvmi Could you do it or give me admin rights for this repo? Thanks

**Comment by mihai-vlc** [comment]
You should have full access now

**Comment by Ne4istb** [comment]
@ionutvmi Thanks
