### ISSUE TITLE
How to handle an empty string '' 

### ISSUE THREAD

**Issue by st-clair-clarke** [VerbalExpressions/DartVerbalExpressions#5]
Hi 
Andri,

I have the following
RegExp wordMatcherOptional = new VerbalExpression( ).startOfLine( ).range(
    [new Range( 'a', 'z' )] ).oneOrMore( ).withAnyCase( ).anyOf( "' -" )
    .zeroOrMore( )
    .add( '[a-z]' )
    .zeroOrMore( )
    .or( '\s*' )
    .endOfLine( )
    .toRegExp( );

but the .or( '\s*' ) does NOT handle the empty string. This regex should be valid if a word is present or an empty string is present. How can I handle this empty string.

Cheers

**Comment by Ne4istb** [comment]
@st-clair-clarke 
All methods except add method take value as parameter which will be sanitized before insert into the regex for obvious reasons.
In your case, as I understood you want to have a match either with your regex or an empty string. It could be reached by capturing your regex and say that it should be met zero or once:

``` dart
RegExp wordMatcherOptional = new VerbalExpression( )
.startOfLine( )
.beginCapture()
//.. continue your pipe
.endCapture()
.countRange(0, 1)  // is capture should be matched 0(empty string) or once (your regex)
.endOfLine()
.toRegExp();
```

Hope it will help
