### ISSUE TITLE
Considering method cascades?

### ISSUE THREAD

**Issue by sethladd** [VerbalExpressions/DartVerbalExpressions#6]
Dart supports method cascades. Instead of each method returning `this`, you could instead have the method return `void` and use cascades:

```
  var regex = new VerbalExpression()
   ..startOfLine()
   ..then("http").maybe("s")
   ..then("://")
   ..maybe("www.")
   ..anythingBut(" ")
   ..endOfLine();
```

Method cascades don't force the API designer to think in fluent APIs or returning `this`. All APIs can become fluent.

Thoughts?

**Comment by Ne4istb** [comment]
@sethladd Good point.
This library was created from the point of builder pattern. But, really, this approach will help us to get rid of most returns and simplify library usage like: 

``` dart
var regex = new VerbalExpression()
   ..startOfLine()

//do something specific

regex
   .then("http")
   ..maybe("s");

//do something specific

regex
   .then("://")
   ..endOfLine();
```

instaed of:

``` dart
var regex = new VerbalExpression()
   .startOfLine()

//do something specific

regex = regex
   .then("http")
   .maybe("s");

//do something specific

regex = regex
   .then("://")
   .endOfLine();
```

Will think about it and, most of all will change it soon.

**Comment by sethladd** [comment]
Thanks!
