### ISSUE TITLE
How to do `*?` "Between zero and unlimited times, as few times as possible"

### ISSUE THREAD

**Issue by kasperpeulen** [VerbalExpressions/DartVerbalExpressions#8]
How to do `*?` 

I see maybe, and I see zeroOrMore,but I don't see how to combine them.

**Comment by Ne4istb** [comment]
Sorry, cannot get a point. 
From my perspective '_' and '_?' are equal because maybe(?) means there is either zero occurrence or one and zeroOrMore(*) mean there is either zero occurrence or more. In combination, it will produce   either zero occurrence or more.

Could you provide a use case where you are using it?

**Comment by kasperpeulen** [comment]
I'm not a regex expert myself, but regex101.com explains it like this:

Quantifier: *? Between zero and unlimited times, as few times as possible, expanding as needed [lazy]
Quantifier: \* Between zero and unlimited times, as many times as possible, giving back as needed [greedy]
Quantifier: ? Between zero and one time, as many times as possible, giving back as needed [greedy]

There is a difference.

Say I have this regexp:
`[ab]*a`

And this test string:
`ababab`

Then it matches the first 5.

With this regexp: `[ab]?a`
It matches only the first.

**Comment by Ne4istb** [comment]
Good point, thanks for notice.

Here is another example;
**Input**: _'greedy can be dangerous at times'_
_'a.*a'_ returns _'an be dangerous a'_
_'a.*?a'_ returns _'an be da'_

I'l extend zeroOrMore with optional parameter isLazy for this case.

**Comment by Ne4istb** [comment]
If you need it right now you can use **.add('*?')**.

**Comment by kasperpeulen** [comment]
thanks !
