### ISSUE TITLE
Add a "non-capture" flag/param to all methods with implicit capture groups

### ISSUE THREAD

**Issue by bjesuiter** [VerbalExpressions/DartVerbalExpressions#9]
Hey Team, 

is it possible to add a flag/param to all methods creating implicit capture groups whether to capture the group or not? 

The problems with the current implementation are lower execution performance caused by these many capturing groups as well as confusing access to user defined capture groups, as the user has to guess how many implicit capture groups were created.

**Comment by Ne4istb** [comment]
@Linkmaster08 has sense, will look at it, thanks for feedback.
